package org.example;

public enum RecordType {
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    INVENTORY_ADDED,
    INVENTORY_REMOVED,
    SHIPMENT_DISPATCHED,
    SHIPMENT_DELIVERED,
    PAYMENT_RECEIVED,
    PAYMENT_REFUNDED,
    STOCK_ADJUSTED
}

